// =============================================================================
// src/improve/judge.ts — LLM-as-a-Judge pipeline for memory strategy eval.
//
// Design choices (all research-backed — see cli-sessions/bhive-v2-research.md):
//   • Uses a SEPARATE model from the actor to avoid self-preference bias
//   • Temperature 0 — deterministic, reproducible
//   • k=3 samples, median per dimension — single samples are noise
//   • Rationale fields come BEFORE scores in JSON schema (model reasons first)
//   • 1-5 behavioral Likert scale (1-10 compresses to 7-9 in practice)
//   • ACCEPT_MARGIN of +0.05 prevents churn from judge noise
//
// Config (env vars):
//   JUDGE_API_KEY       — API key for the judge model (defaults to MY_KEY)
//   JUDGE_MODEL_ID      — Model to use (default: claude-haiku-4-5)
//   JUDGE_SAMPLES       — How many times to sample (default: 3)
//   ACCEPT_MARGIN       — Minimum delta to accept a proposal (default: 0.05)
// =============================================================================

import Anthropic from "@anthropic-ai/sdk";
import { AgentMemory, AgentIdentity } from "../types";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface JudgeDimScores {
  density: number;        // 1-5: how well key info is surfaced without noise
  actionability: number;  // 1-5: does it prime the agent to act this tick
  fidelity: number;       // 1-5: faithfully reflects underlying raw memory
  tokenEfficiency: number;// 1-5: concise, max signal per token
}

export interface JudgeRunResult {
  scores: JudgeDimScores;
  compositeScore: number; // 0.0-1.0 normalized from (mean of 1-5 dims - 1) / 4
  rationale: {
    densityAudit: string;
    actionabilityAudit: string;
    fidelityAudit: string;
    efficiencyAudit: string;
  };
  passed: boolean;
  rawResponse: string;
}

export interface JudgeResult {
  medianScores: JudgeDimScores;
  medianComposite: number; // 0.0-1.0
  samples: JudgeRunResult[];
  passed: boolean;
}

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const JUDGE_MODEL_ID = process.env.JUDGE_MODEL_ID ?? "claude-haiku-4-5";
const JUDGE_SAMPLES = parseInt(process.env.JUDGE_SAMPLES ?? "3", 10);
const JUDGE_PASS_THRESHOLD = 0.6; // composite >= 0.6 to pass a single sample

// ---------------------------------------------------------------------------
// The Judge Prompt
// Key rules:
//   1. XML-delimited inputs prevent the agent's output from hijacking instructions
//   2. rationale fields come BEFORE numeric scores in the JSON
//   3. Strict 1-5 with behavioral anchors for each integer
// ---------------------------------------------------------------------------

function buildJudgePrompt(
  rawMemory: AgentMemory,
  identity: AgentIdentity,
  contextPrompt: string
): string {
  return `You are an expert evaluator of AI agent cognitive architectures.
Your task: evaluate the quality of a synthesized "context prompt" generated by a Memory Strategy module.
The context prompt is what gets injected into an AI agent's session each tick to orient its behavior.

<RAW_AGENT_MEMORY>
${JSON.stringify(rawMemory, null, 2)}
</RAW_AGENT_MEMORY>

<AGENT_IDENTITY>
Name: ${identity.name}
Persona: ${identity.persona}
</AGENT_IDENTITY>

<SYNTHESIZED_CONTEXT_PROMPT>
${contextPrompt}
</SYNTHESIZED_CONTEXT_PROMPT>

Evaluate the synthesized context prompt against the raw memory on EXACTLY these 4 dimensions.
Use a strict 1-5 integer scale with these behavioral anchors:

1. density (Information Density & Saliency)
   1 = Flooded with raw JSON noise, or completely empty
   2 = Contains most facts but with substantial irrelevant boilerplate
   3 = Contains main facts, some noise present
   4 = Well-distilled, mostly high-signal
   5 = Distills complex state into crisp, high-signal needles — no filler

2. actionability (Next-Action Priming)
   1 = Pure passive data dump, no behavioral direction for this tick
   2 = Mentions some state but no clear action cues
   3 = Mentions notifications/activity but does not connect to concrete actions
   4 = Clearly suggests what the agent should do next
   5 = Directly primes which notifications to handle, what to respond to, active cooldowns

3. fidelity (State Faithfulness / Anti-Hallucination)
   1 = Invents notifications or interactions not in the raw memory, or inverts facts
   2 = Multiple factual inaccuracies or missing critical state
   3 = Minor inaccuracies, mostly faithful
   4 = Fully faithful with one small omission
   5 = 100% faithful to the underlying raw data, nothing invented

4. tokenEfficiency (Conciseness)
   1 = Grossly bloated (>1000 tokens of redundant formatting) OR near-empty (useless)
   2 = Substantially over-verbose, could cut 50%+
   3 = Adequate length, could be 30% more concise
   4 = Good density, minor trimming possible
   5 = Maximally efficient — no wasted tokens, every sentence earns its place

IMPORTANT: You MUST output your reasoning in the rationale fields BEFORE assigning scores.
Return ONLY a valid JSON object — no markdown fences, no extra text — matching this exact schema:

{
  "rationale": {
    "densityAudit": "<your step-by-step analysis of density>",
    "actionabilityAudit": "<your step-by-step analysis of actionability>",
    "fidelityAudit": "<your step-by-step analysis of fidelity vs raw memory>",
    "efficiencyAudit": "<your step-by-step analysis of token efficiency>"
  },
  "scores": {
    "density": <integer 1-5>,
    "actionability": <integer 1-5>,
    "fidelity": <integer 1-5>,
    "tokenEfficiency": <integer 1-5>
  },
  "compositeScore": <float 0.0-1.0, calculated as (mean(scores) - 1) / 4>,
  "passed": <boolean, true if compositeScore >= 0.6>
}`;
}

// ---------------------------------------------------------------------------
// Normalize 1-5 dim scores to 0.0-1.0 composite
// ---------------------------------------------------------------------------

function normalizeScores(scores: JudgeDimScores): number {
  const mean = (scores.density + scores.actionability + scores.fidelity + scores.tokenEfficiency) / 4;
  return Math.max(0, Math.min(1, (mean - 1) / 4));
}

// ---------------------------------------------------------------------------
// Run a single judge sample
// ---------------------------------------------------------------------------

async function runSingleJudgeSample(
  client: Anthropic,
  rawMemory: AgentMemory,
  identity: AgentIdentity,
  contextPrompt: string
): Promise<JudgeRunResult> {
  const prompt = buildJudgePrompt(rawMemory, identity, contextPrompt);

  const response = await client.messages.create({
    model: JUDGE_MODEL_ID,
    max_tokens: 1024,
    temperature: 0, // deterministic — critical for reproducibility
    messages: [{ role: "user", content: prompt }],
  });

  const rawText =
    response.content[0].type === "text" ? response.content[0].text : "";

  // Strip markdown fences if model adds them despite instructions
  const cleaned = rawText
    .replace(/^```(?:json)?\s*/m, "")
    .replace(/\s*```\s*$/m, "")
    .trim();

  let parsed: any;
  try {
    parsed = JSON.parse(cleaned);
  } catch {
    throw new Error(`Judge returned non-JSON response: ${rawText.slice(0, 200)}`);
  }

  const scores: JudgeDimScores = {
    density: Number(parsed?.scores?.density ?? 1),
    actionability: Number(parsed?.scores?.actionability ?? 1),
    fidelity: Number(parsed?.scores?.fidelity ?? 1),
    tokenEfficiency: Number(parsed?.scores?.tokenEfficiency ?? 1),
  };

  const compositeScore = normalizeScores(scores);

  return {
    scores,
    compositeScore,
    rationale: {
      densityAudit: parsed?.rationale?.densityAudit ?? "",
      actionabilityAudit: parsed?.rationale?.actionabilityAudit ?? "",
      fidelityAudit: parsed?.rationale?.fidelityAudit ?? "",
      efficiencyAudit: parsed?.rationale?.efficiencyAudit ?? "",
    },
    passed: compositeScore >= JUDGE_PASS_THRESHOLD,
    rawResponse: rawText,
  };
}

// ---------------------------------------------------------------------------
// Median helper
// ---------------------------------------------------------------------------

function median(values: number[]): number {
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 !== 0
    ? sorted[mid]
    : (sorted[mid - 1] + sorted[mid]) / 2;
}

// ---------------------------------------------------------------------------
// Main exported function — runs k samples and returns median scores
// ---------------------------------------------------------------------------

export async function judgeContextPrompt(
  rawMemory: AgentMemory,
  identity: AgentIdentity,
  contextPrompt: string,
  apiKey?: string
): Promise<JudgeResult> {
  const key = apiKey ?? process.env.JUDGE_API_KEY ?? process.env.MY_KEY ?? "";
  if (!key) {
    throw new Error(
      "No API key for judge. Set JUDGE_API_KEY or MY_KEY environment variable."
    );
  }

  const client = new Anthropic({ apiKey: key });
  const samples: JudgeRunResult[] = [];

  for (let i = 0; i < JUDGE_SAMPLES; i++) {
    const sample = await runSingleJudgeSample(
      client,
      rawMemory,
      identity,
      contextPrompt
    );
    samples.push(sample);
  }

  // Compute median per dimension across all k samples
  const medianScores: JudgeDimScores = {
    density: median(samples.map((s) => s.scores.density)),
    actionability: median(samples.map((s) => s.scores.actionability)),
    fidelity: median(samples.map((s) => s.scores.fidelity)),
    tokenEfficiency: median(samples.map((s) => s.scores.tokenEfficiency)),
  };

  const medianComposite = median(samples.map((s) => s.compositeScore));

  return {
    medianScores,
    medianComposite,
    samples,
    passed: medianComposite >= JUDGE_PASS_THRESHOLD,
  };
}
